### ISSUE TITLE
Support for Gen 3 record mixing?

### ISSUE THREAD

**Issue by ZB-Codes-n-Plays** [Lorenzooone/PokemonGB_Online_Trades#28]
Is this even possible?

**Comment by Lorenzooone** [comment]
Hello,
it would be possible in two ways:
1) With direct data transfers between the Gen 3 games.
2) By implementing the option in https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X first, and then adding the ability to do so in this project as well.

In particular, 1) may be possible in the future, however I have currently no firmware ready to do that in hardware to test things out. It's planned, but not done.
2)  is actually the most likely to work right now. Either by adding it as an option to that software, or by making a version of it which just handles this. However, I'd like to ask you to make an issue at https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X about it, so it's in the right project.

**Comment by ZB-Codes-n-Plays** [comment]
Thanks, I’ll add it!
